# Generated by stoatworks-unraid/scripts/gen-docker.mjs from fleet.json.
# Repo: zero-eq. Edit fleet.json and regenerate — direct edits are overwritten.
#
# Zero EQ Simulator — static site, served by nginx.
#
# There is no build stage: web/public/ is committed to the repo already
# built, so the image is the web server plus those files. Adding a Node stage
# here would be inventing work that has no inputs.

FROM nginx:1.27-alpine

# The snippets directory is not in the nginx:alpine image; conf.d is, but a file
# dropped there is auto-included into the http block, which would apply these
# add_header lines globally instead of per-location and defeat the point.
RUN mkdir -p /etc/nginx/snippets

# Extend the MIME map rather than replacing it. nginx 1.27's mime.types already
# maps .wasm but still has no .mjs, and the obvious fix — a `types { }` block in
# the server config — REPLACES the inherited map instead of adding to it, which
# silently demotes every .css and .js to application/octet-stream. Appending to
# the file itself is the only form that adds. The `nginx -t` below is what
# catches it if this sed ever stops matching.
RUN sed -i 's|^}$|    text/javascript                        mjs;\n}|' /etc/nginx/mime.types \
    && grep -q 'mjs;' /etc/nginx/mime.types

COPY docker/stoatworks-headers.conf /etc/nginx/snippets/stoatworks-headers.conf
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY web/public/ /usr/share/nginx/html/

# _headers is a Cloudflare edge directive file. nginx does not read it, and
# serving it would publish the CSP as a static asset for no reason. Its contents
# have already been translated into the config above.
RUN rm -f /usr/share/nginx/html/_headers /usr/share/nginx/html/_redirects

# Fail the build on a bad config rather than at container start. nginx.conf is
# generated from a _headers file, and a header value that needs quoting
# differently would otherwise produce an image that builds green and then
# crash-loops on deploy. This is also the only syntax check these configs get:
# they were authored on a machine with no nginx and no container runtime.
RUN nginx -t

EXPOSE 80

# busybox wget, present in the alpine base. --spider makes a HEAD-like request
# and sets the exit status, which is all HEALTHCHECK needs.
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD wget -q --spider http://localhost/healthz || exit 1
